#ifndef CC120X_REGISTER_SETTINGS_H
#define CC120X_REGISTER_SETTINGS_H

#include "CC120x.h"


static const registerSetting_t preferredSettingsRX[]=
{
  {IOCFG2,            0x06},
  {SYNC_CFG1,         0xAC},
  {DEVIATION_M,       0xD7},
  {MODCFG_DEV_E,      0x1A},
  {DCFILT_CFG,        0x13},
  {PREAMBLE_CFG0,     0xE3},
  {IQIC,              0x00},
  {CHAN_BW,           0x0D},
  {MDMCFG0,           0x02},
  {SYMBOL_RATE2,      0x5F},
  {SYMBOL_RATE1,      0x75},
  {SYMBOL_RATE0,      0x10},
  {AGC_REF,           0x35},
  {AGC_CS_THR,        0xEC},
  {AGC_CFG3,          0x31},
  {AGC_CFG1,          0x24},
  {AGC_CFG0,          0x9F},
  {FIFO_CFG,          0x00},
  {FS_CFG,            0x14},
  {PKT_CFG2,          0x00},
  {PKT_CFG0,          0x20},
  {ASK_CFG,           0xBF},
  {PKT_LEN,           0xFF},
  {IF_MIX_CFG,        0x1C},
  {FREQOFF_CFG,       0x00},
  {MDMCFG2,           0xFC},
  {FREQ2,             0x56},
  {FREQ1,             0xCC},
  {FREQ0,             0xCC},
  {IF_ADC1,           0xEE},
  {IF_ADC0,           0x10},
  {FS_DIG1,           0x07},
  {FS_DIG0,           0xA0},
  {FS_CAL1,           0x40},
  {FS_CAL0,           0x0E},
  {FS_DIVTWO,         0x03},
  {FS_DSM0,           0x33},
  {FS_DVC0,           0x17},
  {FS_PFD,            0x00},
  {FS_PRE,            0x6E},
  {FS_REG_DIV_CML,    0x1C},
  {FS_SPARE,          0xAC},
  {FS_VCO0,           0xB5},
  {IFAMP,             0x09},
  {XOSC5,             0x0E},
  {XOSC1,             0x03},
};
#endif
